version: '3.3'
services:   
  lena:
    build:
      context: ./lena
      dockerfile: Dockerfile
    container_name: lena
    depends_on:
      - lenaDB
    volumes:
      - ./lena:/var/www/html/
    expose:
      - 80
    environment:
      VIRTUAL_HOST: lena.upf.edu

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - wordpressDB
    volumes:
      - ./wordpress:/var/www/html/ 
    expose:
      - 80
    environment:
      VIRTUAL_HOST: web1.com



  lenaDB:
    container_name: lenaDB
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lenaDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./lenaDB:/home/   

  wordpressDB:
    container_name: wordpressDB
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpressDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./wordpress/lena.dump.191030-0100:/docker-entrypoint-initdb.d/lena.dump.191030-0100

volumes:
  lenaDB:
  wordpressDB:

networks:
  default:
    external:
      name: nginx-proxy  
