version: '3.5'
services:   
  lena:
    build:
      context: ./lena
      dockerfile: Dockerfile
    container_name: lena
    volumes:
      - "NFSLena:/var/www/html/"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: lena.upf.edu
    extra_hosts:
      - "dockerhost:192.168.1.1"
  #Network Container
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


volumes:
  NFSLena:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.1
      device: ":/mnt/lena"


networks:
  default:
    external:
      name: nginx-proxy  
