version: '3.3'
services:
  web1:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: web1
    depends_on:
      - db1
    volumes:
      - ./web1:/var/www/html/
    expose:
      - 80
    environment:
      VIRTUAL_HOST: web1.com
 
  web2:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: web2
    depends_on:
      - db2
    volumes:
      - ./web2:/var/www/html/
    expose:
      - 80
    environment:
      VIRTUAL_HOST: web2.com


  db1:
    container_name: db1
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  db2:
    container_name: db2
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db2 
      MYSQL_USER: root
      MYSQL_PASSWORD: root

volumes:
  db1:
  db2:

networks:
  default:
    external:
      name: nginx-proxy  
